from tkinter import*
root=Tk()
root.title("window")
root.geometry("300x300")
frame=Frame(root)
frame.pack()
leftframe=Frame(root)
leftframe.pack(side=LEFT)
rightframe=Frame(root)
rightframe.pack(side=RIGHT)
btn1=Button(frame,text="submit",fg="green",activebackground="green")
btn1.pack(side=LEFT)
btn2=Button(frame,text="Remove",fg="red",activebackground="red")
btn2.pack(side=RIGHT)
btn3=Button(frame,text="Add",fg="black",activebackground="white")
btn3.pack(side=LEFT)
root.mainloop()
